version: '3'
services:
  ETL:
    image: lionezajoao/etl-bd3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

    depends_on:
      - database

  database:
    image: postgres:16
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge